[build]
publish = "abg-interpreter-app"
functions = "netlify/functions"

[[edge_functions]]
function = "start-ocr"
path = "/api/start-ocr"

[[edge_functions]]
function = "start-analysis"
path = "/api/start-analysis"

[[edge_functions]]
function = "check-status"
path = "/api/check-status"
