# Netlify Configuration File

[build]
  # This tells Netlify that our entire site, including the API folder,
  # lives inside the "abg-interpreter-app" directory.
  base    = "abg-interpreter-app"
  publish = "abg-interpreter-app"
  functions = "abg-interpreter-app/api"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200